version: '2'

services:
  spm-client:
   image: sematext/spm-client
   hostname: spm-client-mongo
   privileged: true
   volumes: 
    # spm-client > v1.31.65 requires access to docker socket
    - /var/run/docker.sock:/var/run/docker.sock
   environment:
    # token mongodb mongo-url
    - SPM_CONFIG=${SPM_TOKEN} mongodb mongodb://mongodb:27017/admin
   links: 
    - mongodb

  mongodb:
   image: mongo:latest
   ports:
    - "27017:27017"


  
