version: '2'

services:
  spm-client:
   image: sematext/spm-client
   hostname: spm-client-httpd
   privileged: true
   volumes: 
    # spm-client > v1.31.65 requires access to docker socket
    - /var/run/docker.sock:/var/run/docker.sock
   environment:
    # token httpd httpd_status_url
    - SPM_CONFIG=${SPM_TOKEN} httpd http://httpd:80/server-status
   links: 
    - httpd

  httpd:
   image: httpd:latest
   ports:
    - "80:80"
   volumes: 
    #  httpd.conf requires following entry: 
    #  LoadModule status_module modules/mod_status.so
    #  <Location /server-status>
    #    SetHandler server-status
    #  </Location>
    - ${PWD}/httpd.conf:/usr/local/apache2/conf/httpd.conf